import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-3">{children}</body>
    </html>
  );
}
