/* Generated by Yosys 0.41+126 (git sha1 855ac285f, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

/* cells_not_processed =  1  */
/* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:1.1-12.10" */
module decoder_test(a, b, en, y);
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:5.5-11.8" */
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:2.11-2.12" */
  input a;
  wire a;
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:2.13-2.14" */
  input b;
  wire b;
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:2.15-2.17" */
  input en;
  wire en;
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:3.22-3.23" */
  output [3:0] y;
  reg [3:0] y;
  not _04_ (
    .A(a),
    .Y(_03_)
  );
  not _05_ (
    .A(b),
    .Y(_01_)
  );
  OR _06_ (
    .A(a),
    .B(b),
    .Y(_00_[0])
  );
  OR _07_ (
    .A(a),
    .B(_01_),
    .Y(_00_[1])
  );
  OR _08_ (
    .A(_03_),
    .B(b),
    .Y(_00_[2])
  );
  AND _09_ (
    .A(a),
    .B(b),
    .Y(_02_)
  );
  not _10_ (
    .A(_02_),
    .Y(_00_[3])
  );
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:5.5-11.8" */
  always @*
    if (!1'h0) y[0] = _00_[0];
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:5.5-11.8" */
  always @*
    if (!1'h0) y[1] = _00_[1];
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:5.5-11.8" */
  always @*
    if (!1'h0) y[2] = _00_[2];
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:5.5-11.8" */
  always @*
    if (!1'h0) y[3] = _00_[3];
endmodule
