/* Generated by Yosys 0.41+126 (git sha1 855ac285f, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

/* cells_not_processed =  1  */
/* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:1.1-16.10" */
module decoder_test(in, out);
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:5.5-15.8" */
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:2.17-2.19" */
  input [1:0] in;
  wire [1:0] in;
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:3.22-3.25" */
  output [3:0] out;
  reg [3:0] out;
  not _04_ (
    .A(in[0]),
    .Y(_03_)
  );
  not _05_ (
    .A(in[1]),
    .Y(_01_)
  );
  OR _06_ (
    .A(in[0]),
    .B(in[1]),
    .Y(_02_)
  );
  not _07_ (
    .A(_02_),
    .Y(_00_[0])
  );
  AND _08_ (
    .A(in[0]),
    .B(_01_),
    .Y(_00_[1])
  );
  AND _09_ (
    .A(_03_),
    .B(in[1]),
    .Y(_00_[2])
  );
  AND _10_ (
    .A(in[0]),
    .B(in[1]),
    .Y(_00_[3])
  );
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:5.5-15.8" */
  always @*
    if (!1'h0) out[0] = _00_[0];
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:5.5-15.8" */
  always @*
    if (!1'h0) out[1] = _00_[1];
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:5.5-15.8" */
  always @*
    if (!1'h0) out[2] = _00_[2];
  /* src = "/home/mark/Grad_Project/VeriTest_clean/web_portal/backend/uploaded_files/decoder_test.v:5.5-15.8" */
  always @*
    if (!1'h0) out[3] = _00_[3];
endmodule
